INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOB_TITLE, GENDER, DATE_OF_BIRTH)
    VALUES ('Vasily', 'Pupkin', '1', 'director', 'MALE', '2017-04-28');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOB_TITLE, GENDER, DATE_OF_BIRTH)
    VALUES ('Rudolph', 'the Deer', '42', 'bottles washer','FEMALE', '2018-08-16');